### ISSUE TITLE
Lentidão na execução do caça palavras

### ISSUE THREAD

**Issue by kluvoo** [AdaoProjects/word_search_flutter#1]
Olá Adão, tudo bem?
Muito bacana o seu caça palavras! 

Porém, clonei o projeto e ao rodar notei uma lentidão excessiva que impedia de selecionar as palavras, porém ao baixar o app diretamente da playstore rodou muito bem, tem alguma ideia do que possa ser?

Outra questão é que aparentemente está pedindo permissão de bluetooth, não compreendo a necessidade.

Agradeço se puder ajudar e obrigado pela atenção.

**Comment by AdaoProjects** [comment]
O bluetooth eu devo ter colocado sem querer msm, obg por avisar. Sobre
rodar o app e ficar lento, vc pode tentar no terminal: flutter run
--release. Esse comando faz ele rodar no release mode e entao ele demora
menos para funcionar e ate abrir dps

Em sex, 10 de set de 2021 14:40, kluvoo ***@***.***> escreveu:

**Comment by AdaoProjects** [comment]
O bluetooth é por causa do admob(aparentemente) que estou tentando implementar. Espero ter ajudado.

**Comment by kluvoo** [comment]
Certo, rodar em release realmente funcionou.

Estou tentando tornar ele mais dinâmico, por exemplo, ao invés daquele array estático de palavras, passar uma lista com por exemplo 1 a n<6 palavras e ele automaticamente construir.

Por curiosidade, vi que você optou por usar Table ao invés de um Grid, algum motivo especial? Teria algum problema a solução da pintura em um Grid?

Como pode perceber, eu tenho algumas dúvidas, rsrs . 
Acho que preciso fechar a Issue, você se incomoda de eu continuar entrando em contato?
Senão, posso te contatar por e-mail ou aqui msm pelo git?

**Comment by AdaoProjects** [comment]
fique a vontade
nao me lembro pq escolhi table mas acho q o grid tem uma seleçao default ou é o tablerow

**Comment by AdaoProjects** [comment]
tlvz o grid resolva alguns bugs que tem no app

**Comment by kluvoo** [comment]
Adão, bom dia!
Tentei entrar em contato contigo no e-mail, mas não consegui.
Tava reconstruindo com base na sua solução, mas encontrei algumas situações que talvez você saiba a razão.

1 - Vi que você usa SetState pra atualizar a lista de pontos, verifiquei que o rebuild da tela está ok, mas por algum motivo ele não renderiza a pintura, (PS. Estou tentando pintar inicialmente só o PanStart, um pontinho ), o engraçado é que quando eu rodo o hot reload, o ponto da pintura é exibido.
 
2 - Em relação ao ponto pintado, ele ta apresentando algumas inconsistências na minha versão, principalmente na vertical, o toque é dado numa posição, mas ele exibe umas 4 casas acima, vi que você usa medidas relativas, mas não consegui entender muito bem a condição de verificação.
A imagem de onde me refiro: https://imgur.com/a/AsJO01O

Se puder ajudar, agradeço

**Comment by AdaoProjects** [comment]
nao sei pq nao ta aparecendo o ponto do startPan,
sobre as medidas tb nao tem muito que eu saiba, os celulares que eu testei funcionou com as medidas que estao no ultimo commit, pq se mudar elas quebraria tb nesses celulares, tem q tipo pensar em outra soluçao...

**Comment by kluvoo** [comment]
Certo!
Agradeço bastante a atenção :)

**Comment by AdaoProjects** [comment]
teve alguns commits atras que eu coloquei medidas erras, a logica dessa codiçao é dividir a table em coordenadas x,y de acordo com o tamanho das linhas e colunas.
